### ISSUE TITLE
Error in find-align-by-correlation

### ISSUE THREAD

**Issue by vladtcvs** [vladtcvs/VStarsStack#120]
```vstarstack fine-shift find-align-by-correlation npy aligns2 aligns1/
...
Traceback (most recent call last):
  File "/home/vlad/.local/bin/vstarstack", line 33, in <module>
    sys.exit(load_entry_point('vstarstack==0.2', 'console_scripts', 'vstarstack')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlad/.local/lib/python3.12/site-packages/vstarstack-0.2-py3.12-linux-x86_64.egg/vstarstack/entry.py", line 35, in main
    vstarstack.tool.usage.run(program_project,
  File "/home/vlad/.local/lib/python3.12/site-packages/vstarstack-0.2-py3.12-linux-x86_64.egg/vstarstack/tool/usage.py", line 152, in run
    run(project, argv[1:], new_base, loaded_submodule.commands, message)
  File "/home/vlad/.local/lib/python3.12/site-packages/vstarstack-0.2-py3.12-linux-x86_64.egg/vstarstack/tool/usage.py", line 156, in run
    submodule(project, argv[1:])
  File "/home/vlad/.local/lib/python3.12/site-packages/vstarstack-0.2-py3.12-linux-x86_64.egg/vstarstack/tool/fine_shift/align_correlation.py", line 115, in align
    pre_align0 = Aligner.deserialize(json.load(fname))
                                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'str' object has no attribute 'read'
```

**Comment by vladtcvs** [comment]
Fixed by https://github.com/vladtcvs/VStarsStack/pull/165
